[versions]

# Minecraft
minecraft = "1.21.3"
loom = "1.8.11"
loader = "0.16.9"

# Dependencies
fabric = "0.109.0+1.21.3"
fabrickotlin = "1.12.2+kotlin.2.0.20"
skyblockapi = "1.0.0-beta.59"
hypixelapi = "1.0.1+build.1+mc1.21"
rconfig = "3.3.0"
rconfigkt = "3.3.0"
olympus = "1.1.0"
rlib = "3.3.0"

# Dev Dependencies
devauth = "1.2.1"
modmenu = "12.0.0-beta.1"

[libraries]

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
fabrickotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabrickotlin" }
skyblockapi = { module = "tech.thatgravyboat:skyblock-api-1.21.3", version.ref = "skyblockapi" }
hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }
rconfig = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21.3", version.ref = "rconfig" }
rconfigkt = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-fabric-1.21.3", version.ref = "rconfigkt" }
olympus = { module = "earth.terrarium.olympus:olympus-fabric-1.21.3", version.ref = "olympus" }
rlib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.3", version.ref = "rlib" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]

loom = { id = "fabric-loom", version.ref = "loom" }